<!DOCTYPE HTML>
<html>

<head>
	<title>Cadastro Atleta</title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<link rel="stylesheet" href="<?= assets()->css('main.css'); ?>" />
	<noscript>
		<link rel="stylesheet" href="<?= assets()->css('noscript.css'); ?>" /></noscript>
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
		<div id="wrapper" class="fade-in">

			<!-- Header -->
			<header id="header">
				<a href="atleta" class="logo">Cadastro Atleta</a>
			</header>

			<!-- Nav -->
			<nav id="nav">
				<ul class="links">
					<li><a href="index">Home</a></li>
					<li class="active"><a href="atleta">Cadastro Atleta</a></li>
				</ul>
			</nav>

			<!-- Main -->
			<div id="main">

				<!-- start: conteúdo central -->
                <div class="form-element">
                    <div class="col-md-12 padding-0">
                        <div class="col-md-12">
                            <div class="panel form-element-padding">
                                <div id="msgformulario" class="alert alert-primary" role="alert">* Campos Obrigatórios!</div>
                                <div class="panel-heading">
                                    <h4>Atleta > Novo</h4>
                                </div>
                                <div class="panel-body" style="padding-bottom:30px;">
                                    <div class="col-md-12">
                                        <form class="cmxform" name="frmAtleta" method="POST" action="<?= url()->route('atleta.salvar'); ?>">
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_nome" class="col-sm-2 control-label text-right">Nome*</label>
                                                <div class="col-sm-10"><input name="nome" required aria-required="true" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_cpf" class="col-sm-2 control-label text-right">CPF*</label>
                                                <div class="col-sm-10"><input name="cpf" required aria-required="true" pattern="[0-9]{3}.[0-9]{3}.[0-9]{3}-[0-9]{2}" placeholder="000.000.000-00" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_dt_nascimento" class="col-sm-2 control-label text-right">Data de Nascimento*</label>
                                                <div class="col-sm-10"><input name="dt_nascimento" required aria-required="true" type="date" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_endereco_rua" class="col-sm-2 control-label text-right">Endereço Rua*</label>
                                                <div class="col-sm-10"><input name="endereco_rua" required aria-required="true" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_endereco_numero" class="col-sm-2 control-label text-right">Endereço Nº*</label>
                                                <div class="col-sm-10"><input name="endereco_numero" required aria-required="true" type="number" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_endereco_bairro" class="col-sm-2 control-label text-right">Endereço Bairro*</label>
                                                <div class="col-sm-10"><input name="endereco_bairro" required aria-required="true" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_endereco_CEP" class="col-sm-2 control-label text-right">Endereço CEP*</label>
                                                <div class="col-sm-10"><input name="endereco_CEP" required aria-required="true" pattern="[0-9]{5}-[0-9]{3}" placeholder="00000-000" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_naturalidade" class="col-sm-2 control-label text-right">Naturalidade*</label>
                                                <div class="col-sm-10"><input name="naturalidade" required aria-required="true" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_problema_saude" class="col-sm-2 control-label text-right">Problema de Saúde</label>
                                                <div class="col-sm-10"><input name="problema_saude" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_alergia" class="col-sm-2 control-label text-right">Alergia</label>
                                                <div class="col-sm-10"><input name="alergia" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_medicamento" class="col-sm-2 control-label text-right">Medicamento</label>
                                                <div class="col-sm-10"><input name="medicamento" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_telefone" class="col-sm-2 control-label text-right">Telefone*</label>
                                                <div class="col-sm-10"><input name="telefone" required aria-required="true" pattern="[0-9]{2} [0-9]{5}-[0-9]{4}" placeholder="00 00000-0000" type="tel" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_email" class="col-sm-2 control-label text-right">Email*</label>
                                                <div class="col-sm-10"><input name="email" required aria-required="true" placeholder="email@email.com" type="email" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_fk_turma_id" class="col-sm-2 control-label text-right">Turma</label>
                                                <div class="col-sm-10">
                                                    <select name="turma_id">
                                                        <?php
                                                            foreach($dados_turma as $count){
                                                        ?>
                                                        <option value="<?=$count->id?>"><?=$count->nome?></option>
                                                        <?php
                                                            }
                                                        ?>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_fk_Responsavel_id" class="col-sm-2 control-label text-right">Responsável</label>
                                                <div class="col-sm-10">
                                                    <select name="responsavel_id">
                                                        <?php
                                                            foreach($dados_responsavel as $count){
                                                        ?>
                                                        <option value="<?=$count->id?>"><?=$count->nome?></option>
                                                        <?php
                                                            }
                                                        ?>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px">
                                                <div class="col-md-3" style="margin-top:10px; float: right">
                                                    <button id="btnEnviar" class="btn ripple btn-raised btn-success" type="submit">
                                                        <div>
                                                            <span class="fa fa-save"></span>
                                                            <span style="margin-left: 10px;">Salvar</span>
                                                            <span class="ink animate" style="height: 87px; width: 87px; top: -35.5px; left: -1px;"></span>
                                                        </div>
                                                    </button>
                                                </div>
                                                <div class="col-md-3" style="margin-top:10px; float: right">
                                                    <button id="btnCancelar" onclick="javascript:window.location.href = '<?= url()->route('index') ?>';" class="btn ripple btn-raised btn-danger" type="reset">
                                                        <div>
                                                            <span class="fa fa-close"></span>
                                                            <span style="margin-left: 10px;">Cancelar</span>
                                                            <span class="ink animate" style="height: 87px; width: 87px; top: -35.5px; left: -1px;"></span>
                                                        </div>
                                                    </button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end: conteúdo central -->

			</div>

			<!-- Copyright -->
			<div id="copyright">
				<ul>
					<li>&copy; Untitled</li>
					<li>Design: <a href="https://html5up.net">HTML5 UP</a></li>
				</ul>
			</div>

		</div>

		<!-- Scripts -->
		<script src="<?= assets()->js("jquery.min.js") ?>"></script>
		<script src="<?= assets()->js("jquery.scrollex.min.js") ?>"></script>
		<script src="<?= assets()->js("jquery.scrolly.min.js") ?>"></script>
		<script src="<?= assets()->js("browser.min.js") ?>"></script>
		<script src="<?= assets()->js("breakpoints.min.js") ?>"></script>
		<script src="<?= assets()->js("util.js") ?>"></script>
		<script src="<?= assets()->js("main.js") ?>"></script>
		</body>

</html>