<?php
if (session()->get('_pag_login')):
    if(session()->get('_erro_login')): ?>
        <div class="alert alert-danger" role="alert"><?= session()->getAndRemove('_msg_login'); ?></div>
    <?php else: ?>
        <div class="alert alert-success" role="alert"><?= session()->getAndRemove('_msg_login'); ?></div>
    <?php endif;

    session()->forget('_pag_login');
    session()->forget('_erro_login');
elseif(!session()->get('_user_status')):
    session()->forget('_pag_login');
    session()->forget('_erro_login');
    redirect()->route('login.index');
endif;
?>

<head>
        <meta charset="utf-8">
        <meta name="robots" content="noindex,nofollow">
        <meta name="description" content="Administrador">
        <meta name="author" content="Isna Nur Azis, Compnum">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Administrador</title>

        <!-- start: Css -->
        <link rel="stylesheet" type="text/css" href="<?=assets()->css('bootstrap.min.css')?>">
        <!-- plugins -->
        <link rel="stylesheet" type="text/css" href="<?=assets()->css('plugins/font-awesome.min.css')?>"/>
        <link rel="stylesheet" type="text/css" href="<?=assets()->css('plugins/summernote.css')?>"/>
        <link rel="stylesheet" type="text/css" href="<?=assets()->css('plugins/simple-line-icons.css')?>"/>
        <link rel="stylesheet" type="text/css" href="<?=assets()->css('plugins/animate.min.css')?>"/>
        <link rel="stylesheet" type="text/css" href="<?=assets()->css('plugins/datatables.bootstrap.min.css')?>"/>
        <link rel="stylesheet" type="text/css" href="<?=assets()->css('plugins/nouislider.min.css')?>"/>
        <link rel="stylesheet" type="text/css" href="<?=assets()->css('plugins/select2.min.css')?>"/>
        <link rel="stylesheet" type="text/css" href="<?=assets()->css('plugins/ionrangeslider/ion.rangeSlider.css')?>"/>
        <link rel="stylesheet" type="text/css" href="<?=assets()->css('plugins/ionrangeslider/ion.rangeSlider.skinFlat.css')?>"/>
        <link rel="stylesheet" type="text/css" href="<?=assets()->css('plugins/bootstrap-material-datetimepicker.css')?>"/>
        <link rel="stylesheet" type="text/css" href="<?=assets()->css('plugins/dropzone.css')?>"/>

        <link href="<?=assets()->css('style.css')?>" rel="stylesheet">
        <!-- end: Css -->

        <link rel="shortcut icon" href="<?= assets()->img('logomi.png') ?>">
        <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
        <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>