            <div id="left-menu">
                <div class="sub-left-menu scroll">
                    <ul class="nav nav-list">
                        <li><div class="left-bg"></div></li>
                        <li class="time">
                            <h1 class="animated fadeInLeft"></h1>
                            <p class="animated fadeInRight"></p>
                        </li>
                        <li class="active ripple"><a href="<?=url()->route('index')?>"><span class="fa fa-home"></span>Início</a></li>
                        <li class="ripple">
                            <a class="tree-toggle nav-header"><span class="fa fa-newspaper-o"></span> Menu
                                <span class="fa-angle-right fa right-arrow text-right"></span>
                            </a>
                            <ul class="nav nav-list tree">
                                <li><a href="<?=url()->route('atleta.index')?>">Atleta</a></li>
                                <li><a href="<?=url()->route('responsavel.index')?>">Responsável</a></li>
                                <li><a href="<?=url()->route('funcionario.index')?>">Funcionário</a></li>
                                <li><a href="<?=url()->route('cargo.index')?>">Cargo</a></li>
                                <li><a href="<?=url()->route('turma.index')?>">Turma</a></li>
                                <li><a href="<?=url()->route('categoria.index')?>">Categoria</a></li>
                                <li><a href="<?=url()->route('clubeFutebol.index')?>">Clube Futebol</a></li>
                                <li><a href="<?=url()->route('franquia.index')?>">Franquia</a></li>
                            </ul>
                        </li>
                        <li class="ripple"><a href="<?=url()->route('login.logout')?>"><span class="fa fa-power-off"></span>Sair</a></li>
                    </ul>
                </div>
            </div>