<!DOCTYPE html>
<html lang="pt-br">
    <!-- start: Head -->
    <?php $this->render('common/head'); ?>
    <!-- end: Head -->
    <body id="mimin" class="dashboard">
        <!-- start: Header -->
        <?php $this->render('common/header'); ?>
        <!-- end: Header --> 

        <div class="container-fluid mimin-wrapper">

            <!-- start: Left Menu -->
            <?php $this->render('common/leftMenu'); ?>
            <!-- end: Left Menu -->

            <!-- start: content -->
            <div id="content">
                <!-- start: Top Menu -->
                <div class="panel">
                    <div class="panel-body">
                        <div class="col-md-12 col-sm-12">
                            <h3 class="animated fadeInLeft">Área Administrativa > Início</h3>

                            <ul class="nav navbar-nav animated fadeInRight">
                                <li><a href="<?=url()->route('index') ?>">Início</a></li>
                                <li><a href="<?=url()->route('atleta.index')?>">Atleta</a></li>
                                <li><a href="<?=url()->route('responsavel.index')?>">Responsável</a></li>
                                <li><a href="<?=url()->route('funcionario.index')?>">Funcionário</a></li>
                                <li><a href="<?=url()->route('cargo.index')?>">Cargo</a></li>
                                <li><a href="<?=url()->route('turma.index')?>">Turma</a></li>
                                <li><a href="<?=url()->route('categoria.index')?>">Categoria</a></li>
                                <li><a href="<?=url()->route('clubeFutebol.index')?>">Clube Futebol</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- end: Top Menu -->

                <!-- start: conteúdo central -->
                <!--
                <div class="col-md-12" style="padding:20px;">
                    <div class="col-md-12 padding-0">
                        <div class="col-md-12 padding-0">
                            <div class="col-md-12 padding-0">
                                <div class="col-md-4">
                                    <div class="panel box-v1">
                                        <div class="panel-heading bg-white border-none">
                                            <div class="col-md-6 col-sm-6 col-xs-6 text-left padding-0">
                                                <h4 class="text-left">Total de acessos</h4>
                                            </div>
                                            <div class="col-md-6 col-sm-6 col-xs-6 text-right">
                                                <h4>
                                                    <span class="icon-user icons icon text-right"></span>
                                                </h4>
                                            </div>
                                        </div>
                                        <div class="panel-body text-center">
                                            
                                            <p>Visualizações de página</p>
                                            <hr/>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="panel box-v1">
                                        <div class="panel-heading bg-white border-none">
                                            <div class="col-md-6 col-sm-6 col-xs-6 text-left padding-0">
                                                <h4 class="text-left">Últimos 12 meses</h4>
                                            </div>
                                            <div class="col-md-6 col-sm-6 col-xs-6 text-right">
                                                <h4>
                                                    <span class="icon-user icons icon text-right"></span>
                                                </h4>
                                            </div>
                                        </div>
                                        <div class="panel-body text-center">
                                            
                                            <p>Visualizações de página</p>
                                            <hr/>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="panel box-v1">
                                        <div class="panel-heading bg-white border-none">
                                            <div class="col-md-6 col-sm-6 col-xs-6 text-left padding-0">
                                                <h4 class="text-left">Últimos 30 dias</h4>
                                            </div>
                                            <div class="col-md-6 col-sm-6 col-xs-6 text-right">
                                                <h4>
                                                    <span class="icon-user icons icon text-right"></span>
                                                </h4>
                                            </div>
                                        </div>
                                        <div class="panel-body text-center">
                                            
                                            <p>Visualizações de página</p>
                                            <hr/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-12" >
                        <div class="panel">
                            <div class="panel-heading-white panel-heading">
                                <h4>Visualizações de páginas dos últimos 12 meses</h4>
                            </div>
                            <div class="panel-body">
                                <div class="col-md-12">
                                    <canvas class="line-chart" width="3" height="1"></canvas>
                                </div>
                            </div>
                        </div>
                    </div>
                </div> -->
                <!-- end: conteúdo central -->
            </div>
            <!-- end: content -->
        </div>

        <!-- start: Mobile -->
        <?php $this->render('common/mobileMenu'); ?>
        <!-- end: Mobile -->

        <!-- start: Javascript -->
        <script src="<?=assets()->js('jquery.min.js');?>"></script>
        <script src="<?=assets()->js('jquery.ui.min.js');?>"></script>
        <script src="<?=assets()->js('bootstrap.min.js');?>"></script>

        <!-- plugins -->
        <script src="<?=assets()->js('plugins/moment.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/chart.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/jquery.nicescroll.js');?>"></script>

        <!-- custom -->
        <script src="<?=assets()->js('main.js');?>"></script>

        <!-- end: Javascript -->
    </body>
</html>