<!DOCTYPE html>
<html lang="pt-br">
    <!-- start: Head -->
    <?php $this->render('common/head'); ?> 
    <!-- end: Head -->

    <body id="mimin" class="dashboard">
        <!-- start: Header -->
        <?php $this->render('common/header'); ?>
        <!-- end: Header --> 

        <div class="container-fluid mimin-wrapper">

            <!-- start: Left Menu -->
            <?php $this->render('common/leftMenu'); ?>
            <!-- end: Left Menu -->

            <!-- start: content -->
            <div id="content">
                <!-- start: Top Menu -->
                <div class="panel">
                    <div class="panel-body">
                        <div class="col-md-12 col-sm-12">
                            <?php if ($dados_atleta): ?> 
                                <h3 class="animated fadeInLeft">Área Administrativa > Atleta > Alterar</h3>
                            <?php else: ?>
                                <h3 class="animated fadeInLeft">Área Administrativa > Atleta > Cadastrar</h3>
                            <?php endif; ?>

                            <ul class="nav navbar-nav animated fadeInRight">
                                <li><a href="<?=url()->route('index') ?>">Início</a></li>
                                <li><a href="<?=url()->route('atleta.index')?>">Atleta</a></li>
                                <li><a href="<?=url()->route('responsavel.index')?>">Responsável</a></li>
                                <li><a href="<?=url()->route('funcionario.index')?>">Funcionário</a></li>
                                <li><a href="<?=url()->route('cargo.index')?>">Cargo</a></li>
                                <li><a href="<?=url()->route('turma.index')?>">Turma</a></li>
                                <li><a href="<?=url()->route('categoria.index')?>">Categoria</a></li>
                                <li><a href="<?=url()->route('clubeFutebol.index')?>">Clube Futebol</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- end: Top Menu -->

                <!-- start: conteúdo central -->
                <div class="form-element">
                    <div class="col-md-12 padding-0">
                        <div class="col-md-12">
                            <div class="panel form-element-padding">
                                <div id="msgformulario" class="alert alert-primary" role="alert">* Campos Obrigatórios!</div>
                                <div class="panel-heading">
                                    <?php if ($dados_atleta): ?>
                                        <h4>Atleta > Alterar</h4>
                                    <?php else: ?>
                                        <h4>Atleta > Novo</h4>
                                    <?php endif; ?>
                                </div>
                                <div class="panel-body" style="padding-bottom:30px;">
                                    <div class="col-md-12">
                                        <form class="cmxform" name="frmAtleta" method="POST" action="<?= url()->route('atleta.salvar'); ?>">
                                            <?php if ($dados_atleta): ?>
                                                <input type="hidden" name="id" value="<?= $dados_atleta->id; ?>">
                                            <?php endif; ?>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_nome" class="col-sm-2 control-label text-right">Nome*</label>
                                                <div class="col-sm-10"><input value="<?= $dados_atleta ? $dados_atleta->nome : '' ?>" name="nome" required aria-required="true" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_cpf" class="col-sm-2 control-label text-right">CPF*</label>
                                                <div class="col-sm-10"><input value="<?= $dados_atleta ? $dados_atleta->cpf : '' ?>" name="cpf" required aria-required="true" pattern="[0-9]{3}.[0-9]{3}.[0-9]{3}-[0-9]{2}" placeholder="000.000.000-00" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_dt_nascimento" class="col-sm-2 control-label text-right">Data de Nascimento*</label>
                                                <div class="col-sm-10"><input value="<?= $dados_atleta ? $dados_atleta->dt_nascimento : '' ?>" name="dt_nascimento" required aria-required="true" type="date" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_endereco_rua" class="col-sm-2 control-label text-right">Endereço Rua*</label>
                                                <div class="col-sm-10"><input value="<?= $dados_atleta ? $dados_atleta->endereco_rua : '' ?>" name="endereco_rua" required aria-required="true" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_endereco_numero" class="col-sm-2 control-label text-right">Endereço Nº*</label>
                                                <div class="col-sm-10"><input value="<?= $dados_atleta ? $dados_atleta->endereco_numero : '' ?>" name="endereco_numero" required aria-required="true" type="number" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_endereco_bairro" class="col-sm-2 control-label text-right">Endereço Bairro*</label>
                                                <div class="col-sm-10"><input value="<?= $dados_atleta ? $dados_atleta->endereco_bairro : '' ?>" name="endereco_bairro" required aria-required="true" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_endereco_CEP" class="col-sm-2 control-label text-right">Endereço CEP*</label>
                                                <div class="col-sm-10"><input value="<?= $dados_atleta ? $dados_atleta->endereco_CEP : '' ?>" name="endereco_CEP" required aria-required="true" pattern="[0-9]{5}-[0-9]{3}" placeholder="00000-000" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_naturalidade" class="col-sm-2 control-label text-right">Naturalidade*</label>
                                                <div class="col-sm-10"><input value="<?= $dados_atleta ? $dados_atleta->naturalidade : '' ?>" name="naturalidade" required aria-required="true" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_problema_saude" class="col-sm-2 control-label text-right">Problema de Saúde</label>
                                                <div class="col-sm-10"><input value="<?= $dados_atleta ? $dados_atleta->problema_saude : '' ?>" name="problema_saude" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_alergia" class="col-sm-2 control-label text-right">Alergia</label>
                                                <div class="col-sm-10"><input value="<?= $dados_atleta ? $dados_atleta->alergia : '' ?>" name="alergia" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_medicamento" class="col-sm-2 control-label text-right">Medicamento</label>
                                                <div class="col-sm-10"><input value="<?= $dados_atleta ? $dados_atleta->medicamento : '' ?>" name="medicamento" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_telefone" class="col-sm-2 control-label text-right">Telefone*</label>
                                                <div class="col-sm-10"><input value="<?= $dados_atleta ? $dados_atleta->telefone : '' ?>" name="telefone" required aria-required="true" pattern="[0-9]{2} [0-9]{5}-[0-9]{4}" placeholder="00 00000-0000" type="tel" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_email" class="col-sm-2 control-label text-right">Email*</label>
                                                <div class="col-sm-10"><input value="<?= $dados_atleta ? $dados_atleta->email : '' ?>" name="email" required aria-required="true" placeholder="email@email.com" type="email" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_fk_turma_id" class="col-sm-2 control-label text-right">Turma*</label>
                                                <div class="col-sm-10">
                                                <select name="turma" id="id" style="margin-top: 0px;">
                                                    <?php
                                                        foreach($dados_turma as $count){
                                                    ?>
                                                    <option value="<?=$count->id?>"><?=$count->nome?></option>
                                                    <?php
                                                        }
                                                    ?>
                                                </select>
                                                </div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_fk_Responsavel_id" class="col-sm-2 control-label text-right">ID Responsável</label>
                                                <div class="col-sm-10"><input value="<?= $dados_atleta ? $dados_atleta->fk_Responsavel_id : '' ?>" name="fk_Responsavel_id" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px">
                                                <div class="col-md-3" style="margin-top:10px; float: right">
                                                    <button id="btnEnviar" class="btn ripple btn-raised btn-success" type="submit">
                                                        <div>
                                                            <span class="fa fa-save"></span>
                                                            <span style="margin-left: 10px;">Salvar</span>
                                                            <span class="ink animate" style="height: 87px; width: 87px; top: -35.5px; left: -1px;"></span>
                                                        </div>
                                                    </button>
                                                </div>
                                                <div class="col-md-3" style="margin-top:10px; float: right">
                                                    <button id="btnCancelar" onclick="javascript:window.location.href = '<?= url()->route('atleta.index') ?>';" class="btn ripple btn-raised btn-danger" type="reset">
                                                        <div>
                                                            <span class="fa fa-close"></span>
                                                            <span style="margin-left: 10px;">Cancelar</span>
                                                            <span class="ink animate" style="height: 87px; width: 87px; top: -35.5px; left: -1px;"></span>
                                                        </div>
                                                    </button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end: conteúdo central -->
            </div>
            <!-- end: content -->
        </div>

        <!-- start: Mobile -->
        <?php $this->render('common/mobileMenu'); ?>
        <!-- end: Mobile -->

        <!-- start: Javascript -->
        <script src="<?=assets()->js('jquery.min.js');?>"></script>
        <script src="<?=assets()->js('jquery.ui.min.js');?>"></script>
        <script src="<?=assets()->js('bootstrap.min.js');?>"></script>

        <script src="<?=assets()->js('plugins/moment.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/jquery.knob.js');?>"></script>
        <script src="<?=assets()->js('plugins/bootstrap-material-datetimepicker.js');?>"></script>
        <script src="<?=assets()->js('plugins/jquery.nicescroll.js');?>"></script>
        <script src="<?=assets()->js('plugins/jquery.mask.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/select2.full.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/nouislider.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/ion.rangeSlider.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/jquery.validate.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/summernote.min.js');?>"></script>

        <script src="<?=assets()->js('main.js');?>"></script>

        <!-- end: Javascript -->
    </body>
</html>