<!DOCTYPE html>
<html lang="pt-br">
    <!-- start: Head -->
    <?php $this->render('common/head'); ?> 
    <!-- end: Head -->

    <body id="mimin" class="dashboard">
        <!-- start: Header -->
        <?php $this->render('common/header'); ?>
        <!-- end: Header --> 

        <div class="container-fluid mimin-wrapper">

            <!-- start: Left Menu -->
            <?php $this->render('common/leftMenu'); ?>
            <!-- end: Left Menu -->

            <!-- start: content -->
            <div id="content">
                <!-- start: Top Menu -->
                <div class="panel">
                    <div class="panel-body">
                        <div class="col-md-12 col-sm-12">
                            <?php if ($dados_turma): ?> 
                                <h3 class="animated fadeInLeft">Área Administrativa > Turma > Alterar</h3>
                            <?php else: ?>
                                <h3 class="animated fadeInLeft">Área Administrativa > Turma > Cadastrar</h3>
                            <?php endif; ?>

                            <ul class="nav navbar-nav animated fadeInRight">
                                <li><a href="<?=url()->route('index') ?>">Início</a></li>
                                <li><a href="<?=url()->route('atleta.index')?>">Atleta</a></li>
                                <li><a href="<?=url()->route('responsavel.index')?>">Responsável</a></li>
                                <li><a href="<?=url()->route('funcionario.index')?>">Funcionário</a></li>
                                <li><a href="<?=url()->route('cargo.index')?>">Cargo</a></li>
                                <li><a href="<?=url()->route('turma.index')?>">Turma</a></li>
                                <li><a href="<?=url()->route('categoria.index')?>">Categoria</a></li>
                                <li><a href="<?=url()->route('clubeFutebol.index')?>">Clube Futebol</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- end: Top Menu -->

                <!-- start: conteúdo central -->
                <div class="form-element">
                    <div class="col-md-12 padding-0">
                        <div class="col-md-12">
                            <div class="panel form-element-padding">
                                <div id="msgformulario" class="alert alert-primary" role="alert">* Campos Obrigatórios!</div>
                                <div class="panel-heading">
                                    <?php if ($dados_turma): ?>
                                        <h4>Turma > Alterar</h4>
                                    <?php else: ?>
                                        <h4>Turma > Novo</h4>
                                    <?php endif; ?>
                                </div>
                                <div class="panel-body" style="padding-bottom:30px;">
                                    <div class="col-md-12">
                                        <form class="cmxform" name="frmCadAulas" method="POST" action="<?= url()->route('turma.salvar'); ?>">
                                            <?php if ($dados_turma): ?>
                                                <input type="hidden" name="id" value="<?= $dados_turma->id; ?>">
                                            <?php endif; ?>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_nome" class="col-sm-2 control-label text-right">Nome*</label>
                                                <div class="col-sm-10"><input value="<?= $dados_turma ? $dados_turma->nome : '' ?>" name="nome" required aria-required="true" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_nome" class="col-sm-2 control-label text-right">Turno*</label>
                                                <div class="col-sm-10"><input value="<?= $dados_turma ? $dados_turma->turno : '' ?>" name="turno" required aria-required="true" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_nome" class="col-sm-2 control-label text-right">Horario Inicial*</label>
                                                <div class="col-sm-10"><input value="<?= $dados_turma ? $dados_turma->horario_inicial : '' ?>" name="horario_inicial" required aria-required="true" type="time" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_nome" class="col-sm-2 control-label text-right">Horario Termino*</label>
                                                <div class="col-sm-10"><input value="<?= $dados_turma ? $dados_turma->horario_termino : '' ?>" name="horario_termino" required aria-required="true" type="time" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_nome" class="col-sm-2 control-label text-right">Categoria*</label>
                                            <div class="col-sm-10">
                                                <select name="categoria" id="id" style="margin-top:0px;">
                                                    <?php
                                                        foreach($dados_categoria as $count):
                                                    ?>
                                                    <option value="<?= $count->id ?>"><?= $count->nome ?></option>
                                                    <?php
                                                        endforeach;
                                                    ?>
                                                </select>
                                            </div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_nome" class="col-sm-2 control-label text-right">Franquia*</label>
                                            <div class="col-sm-10">
                                                <select name="franquia" id="id" style="margin-top:0px;">
                                                    <?php
                                                        foreach($dados_franquia as $count):
                                                    ?>
                                                    <option value="<?= $count->id ?>"><?= $count->nome ?></option>
                                                    <?php
                                                        endforeach;
                                                    ?>
                                                </select>
                                            </div>
                                            </div>


                                            <div class="col-md-12" style="padding-bottom: 10px">
                                                <div class="col-md-3" style="margin-top:10px; float: right">
                                                    <button id="btnEnviar" class="btn ripple btn-raised btn-success" type="submit">
                                                        <div>
                                                            <span class="fa fa-save"></span>
                                                            <span style="margin-left: 10px;">Salvar</span>
                                                            <span class="ink animate" style="height: 87px; width: 87px; top: -35.5px; left: -1px;"></span>
                                                        </div>
                                                    </button>
                                                </div>
                                                <div class="col-md-3" style="margin-top:10px; float: right">
                                                    <button id="btnCancelar" type="reset" onclick="javascript:window.location.href = '<?=url()->route('turma.index')?>';" class="btn ripple btn-raised btn-danger">
                                                        <div>
                                                            <span class="fa fa-close"></span>
                                                            <span style="margin-left: 10px;">Cancelar</span>
                                                            <span class="ink animate" style="height: 87px; width: 87px; top: -35.5px; left: -1px;"></span>
                                                        </div>
                                                    </button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end: conteúdo central -->
            </div>
            <!-- end: content -->
        </div>

        <!-- start: Mobile -->
        <?php $this->render('common/mobileMenu'); ?>
        <!-- end: Mobile -->

        <!-- start: Javascript -->
        <script src="<?=assets()->js('jquery.min.js');?>"></script>
        <script src="<?=assets()->js('jquery.ui.min.js');?>"></script>
        <script src="<?=assets()->js('bootstrap.min.js');?>"></script>

        <script src="<?=assets()->js('plugins/moment.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/jquery.knob.js');?>"></script>
        <script src="<?=assets()->js('plugins/bootstrap-material-datetimepicker.js');?>"></script>
        <script src="<?=assets()->js('plugins/jquery.nicescroll.js');?>"></script>
        <script src="<?=assets()->js('plugins/jquery.mask.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/select2.full.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/nouislider.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/ion.rangeSlider.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/jquery.validate.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/summernote.min.js');?>"></script>

        <script src="<?=assets()->js('main.js');?>"></script>

        <script type="text/javascript">
            $(document).ready(function () {

                $('#summernote').summernote({
                    height: 400,
                    toolbar: [
                        // [groupName, [list of button]]
                        ['style', ['bold', 'italic', 'underline', 'clear']],
                        ['font', ['strikethrough', 'superscript', 'subscript']],
                        ['picture', ['picture']],
                        ['video', ['video']]
                    ]
                });

                var valor = $("#conteudo").text();
                $('.note-editable').html(valor);
            });

            function validacaoF(form) {
                $('#lbl_titulo').removeClass('alertaFrm');
                $('#lbl_chamada').removeClass('alertaFrm');

                if (form.titulo.value.replace(/^\s+|\s+$/g, "").length <= 3) {
                    form.titulo.focus();
                    $('#msgformulario').html('Título inválido! Informe-o corretamente.');
                    $('#msgformulario').removeClass('alert-primary');
                    $('#msgformulario').addClass('alert-danger');
                    $('#lbl_titulo').addClass('alertaFrm');
                    return false;
                } else if (form.chamada.value.replace(/^\s+|\s+$/g, "").length <= 3) {
                    form.chamada.focus();
                    $('#msgformulario').html('Chamada inválida! Informe-a corretamente.');
                    $('#msgformulario').removeClass('alert-primary');
                    $('#msgformulario').addClass('alert-danger');
                    $('#lbl_chamada').addClass('alertaFrm');
                    return false;
                }
            }

            function event_btnEnviarClick()
            {
                var valor = $('.note-editable').html();
                $("#conteudo").text(valor);

                if (validacaoF(document.frmCadAulas) != false) {
                    document.frmCadAulas.submit();
                } else {
                    return false;
                }
            }
            $('#btnEnviar').click(event_btnEnviarClick);
        </script>
        <!-- end: Javascript -->
    </body>
</html>